# Generated by Django 4.2 on 2024-03-10 10:22

from django.db import migrations, models
import phonenumber_field.modelfields
import users.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("email", models.EmailField(max_length=60, unique=True)),
                (
                    "first_name",
                    models.CharField(blank=True, max_length=30, validators=[users.validators.validate_name_field]),
                ),
                (
                    "last_name",
                    models.CharField(blank=True, max_length=30, validators=[users.validators.validate_name_field]),
                ),
                ("phone", phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region="RU")),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
